version: '3'

services:
  fastapi-app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - database
    env_file:
      - .env

  database:
    image: "postgres:latest"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: